config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "/", to: "pages#home", as: "root"
  get "/payments/success", to: "payments#success"

  get "/listings", to: "listings#index", as: "listings"
  post "/listings", to: "listings#create"
  get "/listings/new", to: "listings#new", as: "new_listing"
  get "/listings/:id", to: "listings#show", as: "listing"
  put "/listings/:id", to: "listings#update"
  patch "/listings/:id", to: "listings#update"
  delete "/listings/:id", to: "listings#destroy"
  get "/listings/:id/edit", to: "listings#edit", as: "edit_listing"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
class Breed < ApplicationRecord
    has_many :listings, dependent: :destroy
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :breed
  enum sex: { female: 0, male: 1 }
  validates :title, :breed_id, :sex, :price, :deposit, :date_of_birth, presence: true
  has_one_attached :picture
end 

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_listing, only: [:show]
    before_action :set_user_listing, only: [:edit, :update, :destroy]
    def index
        @listings = Listing.all
    end

    def show
        session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        customer_email: current_user.email,
        line_items: [{
            name: @listing.title,
            description: @listing.description,
            amount: @listing.deposit * 100,
            currency: 'aud',
            quantity: 1,
        }],
        payment_intent_data: {
            metadata: {
                user_id: current_user.id,
                listing_id: @listing.id
            }
        },
        success_url: "#{root_url}payments/success?userId=#{current_user.id}&listingId=#{@listing.id}",
        cancel_url: "#{root_url}listings"
    )

    @session_id = session.id
    end

    def new
        set_breeds_and_sexes
        @listing = Listing.new
    end

    def create

        @listing = current_user.listings.create(listing_params)
        if @listing.errors.any?
            set_breeds_and_sexes
            render "new"
        else 
            redirect_to listings_path
        end
    end

    def edit
        set_breeds_and_sexes
    end

    def update
        @listing = Listing.update(params["id"], listing_params)
        puts @listing
        if @listing.errors.any?
            set_breeds_and_sexes
            render "edit"
        else 
            redirect_to listings_path
        end
    end

    def destroy
        Listing.find(params[:id]).destroy
        redirect_to listings_path
    end

    private

    def set_listing
        @listing = Listing.find(params[:id])
    end

    def set_user_listing
        id = params[:id]
        @listing = current_user.listings.find_by_id(id)
    
        if @listing == nil
            redirect_to listings_path
        end
    end

    def set_breeds_and_sexes
        @breeds = Breed.all
        @sexes = Listing.sexes.keys
    end

    def listing_params
        params.require(:listing).permit(:title, :description, :breed_id, :sex, :city, :state, :price, :deposit, :date_of_birth, :diet, :picture)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        render plain: "home page"
    end

    def not_found
        render plain: "not found"
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    def success

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snakepay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>
<%= link_to "logout", destroy_user_session_path, method: :delete %>

<% if user_signed_in? %>
    <%= link_to "logout", destroy_user_session_path, method: :delete %>
<% else %>
    <%= link_to "login", new_user_session_path %>
<% end %>

app/views/listings/_form.html.erb
<% if listing.errors.any? %>
    <div class="errors">
        <% listing.errors.full_messages.each do |error| %>
            <p><%= error %></p>
        <% end %>
    </div>
<% end %>

<%= form_with model: listing, local: true do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title, value: listing.title %>
    </div>
    <div>
        <%= form.label :description %>
        <%= form.text_area :description, value: listing.description %>
    </div>
    <div>
        <%= form.label :price %>
        <%= form.number_field :price, min: 0, value: listing.price %>
    </div>
    <div>
        <%= form.label :deposit %>
        <%= form.number_field :deposit, min: 0, value: listing.deposit %>
    </div>
    <div>
        <%= form.label :date_of_birth %>
        <%= form.date_field :date_of_birth, value: listing.date_of_birth %>
    </div>
    <div>
        <%= form.label :diet %>
        <%= form.text_field :diet, value: listing.diet %>
    </div>
    <div>
        <%= form.label :breed_id %>
        <%= form.select(:breed_id, breeds.map{|b| [b.name, b.id]}) %>
    </div>

    <% sexes.each do |option| %>
        <div>
            <%= form.radio_button :sex, option %>
            <%= form.label "sex_#{option}".to_sym, option, value: listing.sex %>
        <div>
    <% end %>

    <div>
        <%= form.label :picture %>
        <%= form.file_field :picture, accept: "image/png,image/gif,image/jpeg,image/jpg", value: listing.picture %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>

<%= render "form", listing: @listing, breeds: @breeds, sexes: @sexes %>

app/views/listings/index.html.erb
<h1>Snakes for sale</h1>

<%= link_to "create listing", new_listing_path %>
<div class="listings">
<%  for listing in @listings %>
    <div class="listing">
        <%= image_tag listing.picture if listing.picture.attached? %>
        <div class="info">
            <div class="info-bar">
                <div>$<%= listing.price%></div>
                <div><%= listing.sex%></div>
                <div><%= listing.date_of_birth%></div>
            </div>
            <%= link_to listing.title, listing_path(listing.id)%>
            <div><%= listing.description %></div>
                        <br/>

        </div>

        <% if current_user.id == listing.user_id%>
            <%= form_with model: listing, local: true, method: "delete" do |form| %>
                <div class="modify-icons">
                    <%= submit_tag "delete", class: "icon" %>
                    <%= link_to "edit", edit_listing_path(listing.id), class: "icon" %>
                </div>
            <% end %>
        <% end %>
    </div>
<% end %>
</div>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render "form", listing: @listing, breeds: @breeds, sexes: @sexes %>

app/views/listings/show.html.erb
<h1><%= @listing.title %></h1>

<h2>Description</h2>
<p><%= @listing.description %></p>

<button data-stripe="payment">
  Pay Deposit <%= number_to_currency(@listing.deposit) %>
</button>

<script src="https://js.stripe.com/v3/"></script>

<script>
  document
    .querySelector("[data-stripe='payment']")
    .addEventListener("click", () => {
      const stripe = Stripe(
        "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
      );

      stripe.redirectToCheckout({
        sessionId: "<%= @session_id %>"
      });
    });
</script>

app/views/payments/success.html.erb
You've successfully made a payment! 
<%= link_to "Go To Listings", listings_path%>